version: '3'

services:
  backend:
    build:
      context: ./zoo_backend/virtualZoo
    command: gunicorn virtualZoo.wsgi --bind 0.0.0.0:8000
    ports:
    - "8000:8000"
    depends_on:
    - db
  frontend:
    build:
      context: ./zoo_frontend
    volumes:
      - react_build:/react_frontend/build
    depends_on:
    - db
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react_frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
  postgres_data: